alias cpsan='g++ \
	-std=gnu++17 \
	-DLOCAL \
	-pedantic \
	-Wall \
	-Wextra \
	-Wconversion \
	-Wshadow \
	-Wfloat-equal \
	-Wmisleading-indentation \
	-Wimplicit-fallthrough \
	-Wlogical-op \
	-Wduplicated-cond \
	-Wduplicated-branches \
	-Wuseless-cast \
	-Wno-sign-conversion \
	-Wno-unused-const-variable \
	-D_GLIBCXX_DEBUG \
	-ggdb3 \
	-fno-omit-frame-pointer \
	-fsanitize=undefined,float-divide-by-zero,float-cast-overflow,address'